source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'DBProfileViewController_Example', :exclusive => true do
  pod "DBProfileViewController", :path => "../"
  pod "FXBlurView", "~> 1.6.4"
end

target 'DBProfileViewController_Tests', :exclusive => true do
  pod "DBProfileViewController", :path => "../"
end
