source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

#inhibit_all_warnings!

target 'DBProfileViewController_Example' do
    pod 'DBProfileViewController', :path => '../'
    pod 'FXBlurView', '~> 1.6.4'
    
    target 'DBProfileViewController_Tests' do
        inherit! :search_paths
        pod 'FBSnapshotTestCase'
    end
end
