language: objective-c
osx_image: xcode7.3
cache: cocoapods
podfile: Example/Podfile

# skip pod install on travis-ci
# since we check-in the pods folder, etc. this isn't needed
install: true

script:
- set -o pipefail && xcodebuild test -workspace DBProfileViewController.xcworkspace -scheme DBProfileViewControllerTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
